### ISSUE TITLE
Prevent flash of content before element upgraded

### ISSUE THREAD

**Issue by bedeoverend** [simplaio/default-content#5]
Before an element is upgraded - i.e. the custom element is registered and the tag (in this case `default-content`) is upgraded to the custom prototype, that element is treated as though it were a plain `div`. Therefore the innerHTML of `default-content` will be rendered until the upgrade happens.

We need to prevent this by hiding default content, probably by using a style tag in the head of the document that is removed on upgrade of `default-content`.

**Comment by seaneking** [comment]
@bedeoverend is this still relevant?

**Comment by bedeoverend** [comment]
Nah @seaneking I'll close this now. It's been fixed in the bootscript. This should technically never have been in default-content as its not something it should be concerned about anyway
